version: '3.1'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: devdojo
      MYSQL_DATABASE: devdojo
    volumes:
      - microservices_devdojo:/var/lib/mysql

volumes:
  microservices_devdojo: